library(shiny)
library(shinyWidgets)
library(shinyjs)
library(vembedr)

ui <- fluidPage(
  setBackgroundColor(
    color = c("gold", "darkorange"),
    gradient = "linear",
    direction = "bottom"
  ),
  titlePanel("Programming for Data Science: Shiny app development assignment by 19MIA1074"),
  sidebarLayout(
    sidebarPanel(
    tags$style(".well {background-color:orange;}"),
    strong("Introduction:",style = "font-size:28px;"),
    br(),
    em("Hello viewers, as a part of my",span("programming for data science assignment", style = "color:red"), "this app was develpoed by me displaying some knowledge about the ",span("first saga",style = "color:red"),"of the famous",span("Dragon Ball",style = "color:red"),"anime.",style = "font-size:22px;"),
    br(),
    br(),
    img(src="gif.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em(span("Dragon Ball",style = "color:lime"),"is an adaptation of the first portion of",span("Akira Toriyama's Dragon Ball",style = "color:lime"),"manga. It is composed of 153 episodes around 20-minutes long and ran on",span("Fuji TV",style = "color:lime"),"from February 26, 1986 to April 12, 1989. The series average rating was 21.2%, with its maximum being 29.5% (",span("Episode 47",style = "color:lime"),") and its minimum being 13.7% (",span("Episode 110",style = "color:lime"),"). Despite its success, Dragon Ball was overshadowed by its more action-oriented sequel series, ",span("Dragon Ball Z",style = "color:lime"),". Dragon Ball depicted ",span("Goku",style = "color:lime"),"'s childhood, while ",span("Dragon Ball Z",style = "color:lime"),"depicted his adulthood. Both are adapted from the same manga.",style = "font-size:22px;"),
    br(),
    br(),
    em("Dragon Ball is also the first anime of it's kind followed by its sequels like ",span("Dragon Ball Z",style = "color:lime"),",",span("Dragon Ball Super",style = "color:lime")," etc.",style = "font-size:22px;"),
    br(),
    br(),
    strong("Dragon Ball Franchise:",style = "font-size:28px;"),
    br(),
    br(),
    em("Here links have been used to navigate to the respective anime to learn about them. Just click on the below links(names) to navigate to the anime of your wish",style = "font-size:22px;"),
    br(),
    br(),
    a("1. Dragon Ball",href = "https://dragonball.fandom.com/wiki/Dragon_Ball_(anime)",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("2. Dragon Ball Z",href = "https://dragonball.fandom.com/wiki/Dragon_Ball_Z",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("3. Dragon Ball GT(Unofficial)",href = "https://dragonball.fandom.com/wiki/Dragon_Ball_GT",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("4. Dragon Ball Super",href = "https://dragonball.fandom.com/wiki/Dragon_Ball_Super_(anime)",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    br(),
    strong("List of Sagas in the Dragon Ball anime:",style = "font-size:28px;"),
    br(),
    br(),
    em("Here links have been used to navigate to the respective sagas to learn about them. Just click on the below links(names) to navigate to the sagas of your wish",style = "font-size:22px;"),
    br(),
    br(),
    a("1. Emperor Pilaf Saga (Episodes 1-13; originally The Saga of Goku)",href = "https://dragonball.fandom.com/wiki/Emperor_Pilaf_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("2. Tournament Saga (Episodes 14-28)",href = "https://dragonball.fandom.com/wiki/Tournament_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("3. Red Ribbon Army Saga (Episodes 29-45)",href = "https://dragonball.fandom.com/wiki/Red_Ribbon_Army_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("4. General Blue Saga (Episodes 46-57)",href = "https://dragonball.fandom.com/wiki/General_Blue_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("5. Commander Red Saga (Episodes 58-67)",href = "https://dragonball.fandom.com/wiki/Commander_Red_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("6. Fortuneteller Baba Saga (Episodes 68-83)",href = "https://dragonball.fandom.com/wiki/Fortuneteller_Baba_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("7. Tien Shinhan Saga (Episodes 84-101)",href = "https://dragonball.fandom.com/wiki/Tien_Shinhan_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("8. King Piccolo Saga (Episodes 102-122)",href = "https://dragonball.fandom.com/wiki/King_Piccolo_Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("9. Piccolo Jr. Saga (Episodes 123-153)",href = "https://dragonball.fandom.com/wiki/Piccolo_Jr._Saga",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    br(),
    strong("List of charaters in the Dragon Ball anime:",style = "font-size:28px;"),
    br(),
    br(),
    em("Here links have been used to navigate to the respective characters to learn about them. Just click on the below links(names) to navigate to the characters of your wish",style = "font-size:22px;"),
    br(),
    br(),
    a("1. Goku",href = "https://dragonball.fandom.com/wiki/Goku",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("2. Bulma",href = "https://dragonball.fandom.com/wiki/Bulma",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("3. Oolong",href = "https://dragonball.fandom.com/wiki/Oolong",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("4. Master Roshi",href = "https://dragonball.fandom.com/wiki/Master_Roshi",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("5. Turtle",href = "https://dragonball.fandom.com/wiki/Turtle",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("6. Yamcha",href = "https://dragonball.fandom.com/wiki/Yamcha",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("7. Puar",href = "https://dragonball.fandom.com/wiki/Puar",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("8. Ox-King",href = "https://dragonball.fandom.com/wiki/Ox-King",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("9. Chi-Chi",href = "https://dragonball.fandom.com/wiki/Chi-Chi",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("10. Krillin",href = "https://dragonball.fandom.com/wiki/Krillin",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("11. Launch",href = "https://dragonball.fandom.com/wiki/Launch",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("12. Suno",href = "https://dragonball.fandom.com/wiki/Suno",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("13. Nam",href = "https://dragonball.fandom.com/wiki/Nam",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("14. Android 8",href = "https://dragonball.fandom.com/wiki/Android_8",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("15. Dr. Breif",href = "https://dragonball.fandom.com/wiki/Dr._Brief",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("16. Panchy",href = "https://dragonball.fandom.com/wiki/Panchy",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("17. Upa",href = "https://dragonball.fandom.com/wiki/Upa",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("18. Bora",href = "https://dragonball.fandom.com/wiki/Bora",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("19. Korin",href = "https://dragonball.fandom.com/wiki/Korin",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("20. Baba",href = "https://dragonball.fandom.com/wiki/Fortuneteller_Baba",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("21. Grandpa Gohan",href = "https://dragonball.fandom.com/wiki/Grandpa_Gohan",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("22. Tien",href = "https://dragonball.fandom.com/wiki/Tien_Shinhan",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("23. Chiaotzu",href = "https://dragonball.fandom.com/wiki/Chiaotzu",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("24. Yajirobe",href = "https://dragonball.fandom.com/wiki/Yajirobe",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("25. Kami",href = "https://dragonball.fandom.com/wiki/Kami",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("26. Mr. Popo",href = "https://dragonball.fandom.com/wiki/Mr._Popo",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("27. Emperor Pilaf",href = "https://dragonball.fandom.com/wiki/Emperor_Pilaf",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("28. Mai",href = "https://dragonball.fandom.com/wiki/Mai",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("29. Shu",href = "https://dragonball.fandom.com/wiki/Shu",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("30. Commander Red",href = "https://dragonball.fandom.com/wiki/Commander_Red",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("31. Staff Officer Black",href = "https://dragonball.fandom.com/wiki/Staff_Officer_Black",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("32. General Blue",href = "https://dragonball.fandom.com/wiki/General_Blue",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("33. Mercenary Tao",href = "https://dragonball.fandom.com/wiki/Mercenary_Tao",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("34. Master Shen",href = "https://dragonball.fandom.com/wiki/Master_Shen",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("35. World Tournament Announcer",href = "https://dragonball.fandom.com/wiki/World_Tournament_Announcer",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("36. King Piccolo",href = "https://dragonball.fandom.com/wiki/King_Piccolo",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("37. Tambourine",href = "https://dragonball.fandom.com/wiki/Tambourine",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("38. Piano",href = "https://dragonball.fandom.com/wiki/Piano",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("39. Piccolo",href = "https://dragonball.fandom.com/wiki/Piccolo",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("40. Narrator",href = "https://dragonball.fandom.com/wiki/Narrator",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("41. Shenron",href = "https://dragonball.fandom.com/wiki/Shenron",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    br(),
    strong("List of charaters in the Emperor Pilaf Saga of the Dragon Ball anime:",style = "font-size:28px;"),
    br(),
    br(),
    em("Here links have been used to navigate to the respective characters to learn about them. Just click on the below links(names) to navigate to the characters of your wish",style = "font-size:22px;"),
    br(),
    br(),
    strong("Main Characters:",style = "font-size:24px;"),
    br(),
    br(),
    a("1. Goku",href = "https://dragonball.fandom.com/wiki/Goku",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("2. Bulma",href = "https://dragonball.fandom.com/wiki/Bulma",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("3. Oolong",href = "https://dragonball.fandom.com/wiki/Oolong",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("4. Yamcha",href = "https://dragonball.fandom.com/wiki/Yamcha",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("5. Puar",href = "https://dragonball.fandom.com/wiki/Puar",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("6. Emperor Pilaf",href = "https://dragonball.fandom.com/wiki/Emperor_Pilaf",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("7. Mai",href = "https://dragonball.fandom.com/wiki/Mai",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("8. Shu",href = "https://dragonball.fandom.com/wiki/Shu",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    br(),
    strong("Supporting Characters:",style = "font-size:24px;"),
    br(),
    br(),
    a("1. Master Roshi",href = "https://dragonball.fandom.com/wiki/Master_Roshi",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("2. Turtle",href = "https://dragonball.fandom.com/wiki/Turtle",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("3. Ox-King",href = "https://dragonball.fandom.com/wiki/Ox-King",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("4. Chi-Chi",href = "https://dragonball.fandom.com/wiki/Chi-Chi",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("5. Shenron",href = "https://dragonball.fandom.com/wiki/Shenron",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("6. Monster Carrot",href = "https://dragonball.fandom.com/wiki/Monster_Carrot",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("7. Sherman Priest",href = "https://dragonball.fandom.com/wiki/Sherman_Priest",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    a("8. Pocawatha",href = "https://dragonball.fandom.com/wiki/Pocawatha",style = "font-size:22px;",style = "font-style:italic"),
    br(),
    br(),
    strong("List of battles fought in the Emperor Pilaf Saga of the Dragon Ball anime:",style = "font-size:28px;"),
    br(),
    br(),
    em("1. ",span("Goku vs. Giant Fish",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("2. ",span("Goku vs. Pterodactyl",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("3. ",span("Goku vs. Wolves (anime only)",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("4. ",span("Goku vs. Bear Thief",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("5. ",span("Goku vs. Oolong",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("6. ",span("Goku vs. Yamcha",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("7. ",span("Goku vs. Yamcha (rematch)",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("8. ",span("Goku vs. Ox-King (anime only)",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("9. ",span("Goku vs. Rabbit Mob",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("10. ",span("Goku, Yamcha, and Puar vs. Monster Carrot",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("11. ",span("Goku and Yamcha vs. Shu's Dog Police (anime only)",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("12. ",span("Goku (Great Ape) vs. Emperor Pilaf, Shu, and Mai",style = "color:brown"),style = "font-size:22px;"),
    br(),
    em("13. ",span("Goku (Great Ape) vs. Yamcha and Puar",style = "color:brown"),style = "font-size:22px;"),
    br(),
    br(),
    strong("Streaming and Download links of the Anime:",style = "font-size:28px;"),
    br(),
    br(),
    strong("Dragon Ball:",style = "font-size:26px;"),
    br(),
    br(),
    strong("Download:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://animekayo.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Stream:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://www.anime-planet.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Dragon Ball Z:",style = "font-size:26px;"),
    br(),
    br(),
    strong("Download:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://animekayo.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Stream:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://www.anime-planet.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Dragon Ball GT:",style = "font-size:26px;"),
    br(),
    br(),
    strong("Download:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://animekayo.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Stream:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://www.anime-planet.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Dragon Ball Super:",style = "font-size:26px;"),
    br(),
    br(),
    strong("Download:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://animekayo.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Stream:",style = "font-size:24px;"),
    br(),
    br(),
    em("Just go to the link and search for the anime over there",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://www.anime-planet.com/", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    strong("Why shades of orange all over the app:",style = "font-size:28px;"),
    br(),
    br(),
    em("As a fan of the protagonist(",span("Son Goku(Kakarot)",style = "color:aqua"),") of Dragon ball and its sequels, I have chosen to maintain the theme of this app in the shades of orange as he prefers clothing of orange shades in the sequels of this Dragon Ball anime series. So as a tribute for him, I have done this.",style = "font-size:22px;"),
    br(),
    br(),
    em("Here are few gifs of this incredible hero:",style = "font-size:22px;"),
    br(),
    br(),
    em("Baby Goku:",style = "font-size:22px;"),
    br(),
    img(src="gif1.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Kid Goku:",style = "font-size:22px;"),
    br(),
    img(src="gif2.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Teen Goku:",style = "font-size:22px;"),
    br(),
    img(src="gif3.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Adult Goku:",style = "font-size:22px;"),
    br(),
    img(src="gif4.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Great Ape Transformation:",style = "font-size:22px;"),
    br(),
    img(src="gif14.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Kaioken Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif5.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif13.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan 2 Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif6.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan 3 Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif7.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan 4 Transformation(",span("Non Canon",style = "color:blue"),"(Doesn't appear in the real Dragon Ball timeline))):",style = "font-size:22px;"),
    br(),
    img(src="gif8.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan God Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif9.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Super Saiyan God Super Saiyan Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif10.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Ultra Instinct(Omen) Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif11.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    em("Goku(Mastered Ultra Instinct Transformation):",style = "font-size:22px;"),
    br(),
    img(src="gif12.gif", align = "center",height='250px',width='250px'),
    br(),
    br(),
    strong("Conclusion:",style = "font-size:28px;"),
    br(),
    br(),
    em("As an anime fan, I'm really impressed by this anime and it's sequels since my childhood as it is the first anime I have ever watched. It used to be aired on the old school ",span("Cartoon Network",style = "color:blue")," channel between 2000 and 2010. I highly recommend you guys to watch this in your life at least once, if you are an anime fan.",style = "font-size:22px;"),
    br(),
    br(),
    em("I would really like to thank the ",span("Fandom",style = "color:yellow")," company for creating such a stunning website for the Dragon Ball fans. If you really are a Dragon Ball fan, then you must have a look at it. Infact, this page helped me a lot in creating my shiny app.",style = "font-size:22px;"),
    br(),
    br(),
    em("Here's the link of that marvellous creation:",style = "font-size:22px;"),
    br(),
    br(),
    a(href="https://dragonball.fandom.com/wiki/Main_Page", class="btn btn-default","Click Here!!",style = "font-size:22px;",style = "background-color: tomato"),
    br(),
    br(),
    em("Thanks a lot guys for going through my shiny app. In fact, this is my first time experience in this domain. In the coming future, I will try to improve more by learning new tricks and hacks. Thanks again for going through. Peace out",style = "font-size:22px;")
    ),
    mainPanel(
      em("Now let's have a look at the ",span("first saga",style = "color:brown")," of ",span("Dragon Ball",style = "color:brown"),", that is, the ",span("Emperor Pilaf Saga",style = "color:brown"),".",style = "font-size:24px;"),
      br(),
      br(),
      strong("A Note to the Viewers:",style = "font-size:30px;"),
      br(),
      br(),
      em("Throughout this webpage I have used colors to highlight important phrases as well as links too. I have given a separate note for each separate areas where links are been provied by me as it is not possible to put all of the content of the anime in a single web page.",style = "font-size:24px;"),
      br(),
      br(),
      strong("Emperor Pilaf Saga:",style = "font-size:30px;"),
      br(),
      br(),
      img(src = 'https://thakortahkastotaku.files.wordpress.com/2017/03/6846_dragon_ball_z_hd_wallpapers.jpg',width = 900,height = 500),
      br(),
      br(),
      em(span("Emperor Pilaf Saga",style = "color:red;"),", also known as ",span("The Saga of Goku",style = "color:red"),", the",span("Goku and Bulma Saga",style = "color:red")," in the Dragon Box release, or as the ",span("Search for the Dragon Ball Saga",style = "color:red")," in ",span("Daizenshuu 2",style = "color:red"),", is the first saga in the ",span("Dragon Ball manga",style = "color:red")," and ",span("anime",style = "color:red"),". The manga volumes that it is made up of are ",span("The Monkey King",style = "color:red")," and ",span("Wish Upon A Dragon",style = "color:red"),". It is in this saga that ",span("Goku",style = "color:red")," and ",span("Bulma",style = "color:red")," meet, and where they also meet allies ",span("Yamcha, Puar, Oolong, Master Roshi, Turtle, Chi-Chi, Ox-King",style = "color:red")," and others. The main antagonist of the saga is ",span("Emperor Pilaf",style = "color:red")," and his underlings, ",span("Shu",style = "color:red")," and ",span("Mai",style = "color:red"),", though technically most of the allies-to-be started out as antagonists.",style = "font-size:24px;"),
      br(),
      br(),
      em("Unlike later sagas, the first adventures are very episodic. Characters and situations are introduced and resolved in single issue/episode and they are connected only via the attempt to locate the ",span("Dragon Balls",style = "color:crimson")," which are the source of most of the battles and challenges which unfold during this saga and much of the series. The anime edition of this saga introduced Emperor Pilaf (and his underlings) much earlier and provided a more cohesive arc over the initial episodes.",style = "font-size:24px;"),
      br(),
      br(),
      em("Some of the characters and situations in this first part of the ",span("Dragon Ball",style = "color:indigo")," plot are rehashed from ",span("Akira Toriyama",style = "color:indigo"),"'s earlier pilot, ",span("Dragon Boy",style = "color:indigo"),". In addition, the influence of the Chinese folk-novel ",span("Journey to the West",style = "color:indigo")," is at its peak at this early stage. This saga has also been retold in the movies ",span("Dragon Ball: Curse of the Blood Rubies",style = "color:indigo")," and ",span("Dragon Ball: The Path to Power",style = "color:indigo"),", and ",span("Dragonball Evolution",style = "color:indigo"),", as well as the illegal movie adaptations ",span("Dragon Ball: Ssawora Son Goku, Igyeora Son Goku",style = "color:indigo")," and ",span("Dragon Ball: The Magic Begins",style = "color:indigo"),", but all feature different villains and some are merged with other sagas.",style = "font-size:24px;"),
      br(),
      br(),
      em("Here are some images of the preview of the saga below:",style = "font-size:24px;"),
      br(),
      br(),
      em("1)",style = "font-size:24px;"),
      img(src = 'https://vignette.wikia.nocookie.net/dragonball/images/3/33/Pilafsaga.jpg/revision/latest?cb=20090826195238',width = 400,height = 400),
      em("2)",style = "font-size:24px;"),
      img(src = 'https://i.pinimg.com/originals/c1/a8/6a/c1a86ac5e86b8f61657d20e12faa6de4.jpg',width = 350,height = 400),
      br(),
      br(),
      em("3)",style = "font-size:24px;"),
      img(src = 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQZvqGbw6PM61NaI_Blfr5WIJnv3rVssqRHZQ&usqp=CAU',width = 400,height = 350),
      br(),
      br(),
      strong("Plot:",style = "font-size:28px;"),
      br(),
      br(),
      strong("Beginning the adventure",style = "font-size:26px;"),
      br(),
      br(),
      em("One day on ",span("Mount Paozu",style = "color:navy"),", a young monkey tailed boy named ",span("Goku",style = "color:navy")," was finished with his daily chores and saw that ",span("his late adoptive grandpa",style = "color:navy"),"'s ",span("Dragon Ball",style = "color:navy")," was glowing, which is the ",span("4-Star Dragon Ball",style = "color:navy"),". Later on when on his way back home with a ",span("Giant Fish",style = "color:navy")," he was going to eat for lunch he was rammed into by a car driven by a young teenage girl named ",span("Bulma",style = "color:navy"),". At first Goku thought the ",span("Dyno Cap",style = "color:navy")," car Bulma was driving was a monster but then revealed she was a human girl. Bulma came with Goku to his house to eat lunch with him but Bulma saw that he had the Dragon Ball she was looking for. Goku refused to give her it and she told him the legend of the dragon known as ",span("Shenron",style = "color:navy"),", and Goku decided to join Bulma on her quest to acquire the seven mystical balls. After encountering a hungry ",span("pterodactyl",style = "color:navy")," the two then set up camp later. Goku was then introduced to technology and was given a bath when Bulma set up the ",span("Capsule House",style = "color:navy"),".",style = "font-size:24px;"),
      br(),
      em("The below image shows the first meet of Goku and Bulma:",style = "font-size:24px;"),
      br(),
      br(),
      img(src = "https://vignette.wikia.nocookie.net/dragonball/images/c/c4/GokumeetsBulma.png/revision/latest/scale-to-width-down/200?cb=20091117175322",width = 350,height = 300),
      br(),
      br(),
      em("The next morning Goku ends up meeting a ",span("Sea Turtle",style = "color:blue")," outside of the house while waiting for Bulma to get ready. Goku and Bulma end up postponing their quest to help the sea turtle. On their way Goku defeats a ",span("Bear Thief",style = "color:blue")," which then impressed Bulma having her more confident in Goku's ability. When they came to the ocean the turtle brought back his master, the Turtle Hermit later to be known as ",span("Master Roshi",style = "color:blue"),". Being thankful for Goku's help he was given the ",span("Flying Nimbus",style = "color:blue")," and Bulma was given another Dragon Ball in the exchange of showing the old master her underwear.",style = "font-size:24px;"),
      br(),
      em("The below image shows Goku receiving the Flying Nimbus for the first time:",style = "font-size:24px;"),
      br(),
      br(),
      div(img(src = 'https://vignette.wikia.nocookie.net/dragonball/images/d/d6/NCOR2.jpg/revision/latest/scale-to-width-down/200?cb=20091030112109',width = 400,height = 350),align = 'right'),
      br(),
      br(),
      strong("Taking on Oolong",style = "font-size:26px;"),
      br(),
      br(),
      em("Three days later, Goku and Bulma end up in ",span("Aru Village",style = "color:deeppink"),", where they end up being mistaken for ",span("Oolong",style = "color:deeppink"),", a ",span("shape shifter",style = "color:deeppink")," who has been kidnapping the daughters of the villagers. When Bulma found out that ",span("Grandma Paozu",style = "color:deeppink"),", an old lady in the village, had a Dragon Ball she forced Goku to disguise himself as ",span("Pocawatha",style = "color:deeppink"),"(Oolong's next target) to find out where Oolong was kidnapping the girls. When the plan ended up failing he decided to take on Oolong in combat and capture him. After Oolong revealed his real form which was a pig he showed the villagers where he kept the daughters and Bulma was given another one of the Dragon Balls by Grandma Paozu.",style = "font-size:24px;"),
      br(),
      em("The below image shows the faceoff between Goku and Oolong:",style = "font-size:24px;"),
      br(),
      br(),
      img(src = "https://vignette.wikia.nocookie.net/dragonball/images/5/52/RobotOolong.png/revision/latest/scale-to-width-down/180?cb=20120713151504",width = 350,height = 300),
      br(),
      br(),
      strong("Dangers in the Diablo Desert",style = "font-size:26px;"),
      br(),
      br(),
      em("After the village was saved Bulma forced Oolong to join them thinking his shape shifting ability would be useful. Oolong who was completely against the idea ended up being controlled by a vitamin Bulma gave him to make him go to the bathroom whenever she says piggy. Bulma ends up losing her Dynocaps and ends up not having any vehicles for the rest of the journey. After walking a couple of miles they end up in the ",span("Diablo Desert",style = "color:mediumorchid")," where Bulma goes crazy and passes out in the heat. While she passes out in the heat a Desert Bandit named ",span("Yamcha",style = "color:mediumorchid")," and his sidekick ",span("Puar",style = "color:mediumorchid"),"(who was a former acquaintance of Oolong) ambush Goku and Oolong and try to rob them. Goku fights back with his power pole revealing to Yamcha that Goku is the grandson of a legendary martial artist named ",span("Gohan",style = "color:mediumorchid"),". Yamcha uses a powerful attack called ",span("Wolf Fang Fist",style = "color:mediumorchid"),", which is Yamcha's signature move, to knock Goku into rocks trapping him under rubble. Just before Oolong gives up his ",span("capsule",style = "color:mediumorchid"),", Goku comes back with a little bit of energy left and sends Yamcha in a rage which is stopped when Bulma wakes up and Yamcha is scared off due to his fear of women.",style = "font-size:24px;"),
      br(),
      em("The below image shows the fight between Yamcha and Goku:",style = "font-size:24px;"),
      br(),
      br(),
      div(img(src = 'https://vignette.wikia.nocookie.net/dragonball/images/e/e3/YamchaVsGoku.png/revision/latest/scale-to-width-down/200?cb=20130701111306',width = 400,height = 350),align = 'right'),
      br(),
      br(),
      em("Later that night in Oolong's ",span("House-Wagon",style = "color:skyblue"),", Bulma is taking a shower when Yamcha and Puar come again to spy on them. Yamcha ends up seeing Bulma naked and then goes to the other window and hears Goku tell Oolong about the Dragon Balls. Yamcha hears the conversation and then dedicates his mission to getting the Dragon Balls instead of robbing them. When Bulma and Goku fall asleep from Oolong's special juice, Oolong is interrupted when trying to search the room Bulma is sleeping in. Puar who is disguised as Goku ends up luring Oolong who is disguised as Bulma out of the trailer for Yamcha to go and steal the balls. Yamcha ends up failing when he sees Bulma completely naked.",style = "font-size:24px;"),
      br(),
      em("The below image shows Yamcha and Puar stalking Goku and the others:",style = "font-size:24px;"),
      br(),
      br(),
      img(src = "https://vignette.wikia.nocookie.net/dragonball/images/a/ae/Yamshastalkstheothers.png/revision/latest/scale-to-width-down/200?cb=20091117175717",width = 350,height = 300),
      br(),
      br(),
      em("The next morning Bulma is disappointed that the only clothes she has that would fit her is a bunny costume. Yamcha who is outside shoots down the house wagon with a bazooka and knocks Bulma out. Goku ends up having a rematch with Yamcha and knocks his tooth out in battle. Yamcha then surrenders and comes up with a different idea and let them collect the Dragon Balls and give them a car with a tracker.",style = "font-size:24px;"),
      br(),
      br(),
      strong("The Destruction of Fire Mountain",style = "font-size:26px;"),
      br(),
      br(),
      em("After traveling awhile they end up at ",span("Fire Mountain",style = "color:red")," which is the site for their sixth Dragon Ball. Oolong was scared to go because he knew legends of the ",span("Ox-King",style = "color:red")," and knew he would kill them. Bulma forced Oolong to come with them to go find the ball. Goku went to the top with the flying nimbus but it was too hot for him to manage. When he got down to tell Bulma the Ox-King began to fight Goku in battle. At first the Ox-King seemed to be much for Goku but when Goku got on the Nimbus the Ox-King changed his mind and asked Goku to go with his daughter ",span("Chi-Chi",style = "color:red")," to get the ",span("Bansho Fan",style = "color:red")," to put out the fire from Master Roshi who was his and Gohan's Martial Arts Teacher.",style = "font-size:24px;"),
      br(),
      br(),
      em("When Goku and Chi-Chi got to Master Roshi's house, Chi-Chi was not convinced that the old man was really Master Roshi so she decided to test him by throwing the blade that was atop her helmet straight at Roshi while his back was turned. Roshi tried to deflect the attack with his can but ended up getting a blow to the head. After Roshi showed his id to the two, he went on to say that he had threw away the Bansho Fan along time ago but agreed to put the fire out himself if he was allowed to touch Bulma's breasts. When they got back to Fire Mountain Master Roshi revealed a powerful technique called the ",span("Kamehameha",style = "color:aqua")," Wave and destroyed the mountain. Under the rubble Bulma found the sixth Dragon Ball. Goku who was amazed by the wave and tried to perform it himself but ended up destroying the car Yamcha had gave them. The Ox-King was thankful for getting rid of the fire and gave them his car. Just before they left Chi-Chi asked Goku if they would ever see each other again and Goku agreed.",style = "font-size:24px;"),
      br(),
      em("The below image shows Master Roshi firing a Kamehameha wave at the mountain:",style = "font-size:24px;"),
      br(),
      br(),
      div(img(src = 'https://vignette.wikia.nocookie.net/dragonball/images/2/22/RoshisKameKameha.png/revision/latest/scale-to-width-down/200?cb=20091117175959',width = 400,height = 350),align = 'right'),
      br(),
      br(),
      strong("Conflict with the Rabbit Mob",style = "font-size:26px;"),
      br(),
      br(),
      em("On their way to the final Dragon Ball, Oolong sees that the car is low on gas and decides to stop at the closest town to fill up. While there everyone looked in fear of Bulma who was still in the Bunny Costume Oolong had given her. While in town, Bulma was able to get free stuff. When she got different clothes on everyone stop being afraid of her because she was mistaken as a member of a local gang called the ",span("Rabbit Mob",style = "color:dodgerblue"),". Once Bulma met back up with Oolong and Goku they see two members of the Rabbit Mob bullying the villagers. When they noticed Bulma they started to hit on her but when she rejected them they got mad and Goku came and defeated the two in a matter of seconds. Afterwards the two called their boss over which then caused the whole town to run in panic. When the boss of the rabbit mob ",span("Monster Carrot",style = "color:dodgerblue")," showed up he turned Bulma into a Carrot with his handshake. Monster Carrot then threatened Goku to not move or he would eat Bulma allowing the two members to beat up Goku. Yamcha and Puar who were still hiding decided to temporarily switch sides and help Goku defeat Monster Carrot. Puar turned into a bird and stole the carrot while Goku and Yamcha tried to fight Monster Carrot. Puar dropped the carrot when crashing into a mushroom tree and Goku caught it. Monster Carrot then got scared off when Puar transformed into him and threatened to touch him. Monster Carrot then turned Bulma back to normal and was tied up with his two minions and taken to the moon where they were forced to make marshmallow treats for children.",style = "font-size:24px;"),
      br(),
      em("The below image shows Monster Carrot threatening to eat Bulma who got turned into a carrot:",style = "font-size:24px;"),
      br(),
      br(),
      img(src = "https://vignette.wikia.nocookie.net/dragonball/images/e/e3/RabbitMob.png/revision/latest/scale-to-width-down/200?cb=20091117180413",width = 350,height = 300),
      br(),
      br(),
      strong("Emperor Pilaf and the Eternal Dragon",style = "font-size:26px;"),
      br(),
      br(),
      em("Goku and Bulma were not the only ones seeking the magical Dragon Balls. A small, blue-skinned man named ",span("Emperor Pilaf",style = "color:crimson")," was also seeking the Balls, with his wish being to become supreme ruler of the entire world. Assisting Pilaf are his two close followers ",span("Shu",style = "color:crimson"),", a small fox-like man, and ",span("Mai",style = "color:crimson"),", a beautiful foot-soldier. Many of Pilaf's attempts to steal the Dragon Balls away from Goku are foiled by the young warrior, causing great embarrassment to the villains. However, he is able to finally steal all seven balls from our heroes by trapping them in a room and knocking them out with sleeping gas. Without delay, Pilaf rushes to his castle and summons the Eternal Dragon, Shenron, but before he can make his one wish come true, Oolong jumps in at the last minute to put a stop to it by wishing for his own pair of women's undergarments, the most comfortable in the world. After doing so the balls gather in the sky and are separated once more, never to be used for another year. An enraged Pilaf imprisons the heroes in his castle.",style = "font-size:24px;"),
      br(),
      em("The below image shows Yamcha, Goku, Bulma, Oolong, and Puar trapped in a room made by Emperor Pilaf:",style = "font-size:24px;"),
      br(),
      br(),
      div(img(src = "https://vignette.wikia.nocookie.net/dragonball/images/2/2e/GokuBulmaOolongPuarYamchaDB.png/revision/latest/scale-to-width-down/180?cb=20100420183943",width = 400,height = 350),align = 'right'),
      br(),
      br(),
      strong("The Great Ape",style = "font-size:26px;"),
      br(),
      br(),
      em("Later that night, Goku tells the story of his grandfather, Gohan, and tells of his untimely demise. A great and terrible beast came upon Gohan's shack one night and crushed the old man to death. This was also the night of a full moon. Upon finishing the story, Goku witnesses the full moon peeking in through the roof of their cell. This causes Goku to lose all sense of himself and transform into a giant, ",span("deadly ape-like monster",style = "color:red"),". The monster immediately proceeds to lay waste to the castle. Pilaf and his minions escape the castle in time, but Yamcha and the rest of the gang must now find a way to help their enraged friend. Puar changes into a pair of scissors and cuts off Goku's tail, changing the frightening beast back into the small, peaceful child. Morning comes and Goku awakes with no memory of the night's events. The experience now confirms to the rest of the gang that it was indeed Goku himself who was responsible for Gohan's tragic death, though all of them agree to never tell Goku as the knowledge would undoubtedly crush the boy's soul.",style = "font-size:24px;"),
      br(),
      em("The below image shows Goku going on a rampage in his Great Ape transformation:",style = "font-size:24px;"),
      br(),
      br(),
      img(src = "https://vignette.wikia.nocookie.net/dragonball/images/9/9c/Runningpilaf.jpg/revision/latest/scale-to-width-down/180?cb=20091003021525",width = 350,height = 300),
      br(),
      br(),
      em("As Goku awakens the next morning naked and missing his tail, Oolong gives him his pants to cover up as Goku goes to find his Power Pole in the ruins of Pilaf's Castle. Bulma and Yamcha decide to become boyfriend and girlfriend as they decides to head back to her hometown of ",span("West City",style = "color:indianred"),". She gives Goku the Dragon Radar so that he may go after his grandfathers Dragon Ball when it can be detected again in a year. As Goku goes his own separate way to get strong and train under Master Roshi, he goes aboard the Flying Nimbus and waves goodbye to his friends for the first time as they fly off in a Capsule plane ending their journey.",style = "font-size:24px;"),
      br(),
      em("The below image shows Goku departing from his friends:",style = "font-size:24px;"),
      br(),
      br(),
      div(img(src = "https://vignette.wikia.nocookie.net/dragonball/images/7/70/Byefriends.jpg/revision/latest/scale-to-width-down/180?cb=20110516045845",width = 400,height = 350),align = 'right'),
      br(),
      br(),
      em("And this marks the end of the Emperor Pilaf Saga and the beginning of the ",span("Tournament Saga",style = "color:skyblue")," as Goku leaves to train with Master Roshi.",style = "font-size:24px;"),
      br(),
      br(),
      em("Here are some videos for the viewers, who had come to know about the ",span("Dragon Ball",style = "color:red")," anime for the first time:",style = "font-size:24px;"),
      br(),
      br(),
      em("1) ",span("Cha-La-Head-Cha-La",style = "color:blue"),"(The opening song of Dragon Ball anime) with the growing stages of Goku as well as the complete story of the anime and its sequels in a nutshell:",style = "font-size:24px;"),
      br(),
      br(),
      embed_url("https://youtu.be/H5opF50Htt8"),
      br(),
      br(),
      em("2) Trailer of Dragon Ball Season 1(Emperor Pilaf Saga):",style = "font-size:24px;"),
      br(),
      br(),
      embed_url("https://youtu.be/TYdcrhyC-8M"),
      br(),
      br(),
      em("3) Birth of a Hero: Son Goku:",style = "font-size:24px;"),
      br(),
      br(),
      embed_url("https://youtu.be/skn1J6ZnCz8")
    )
  )
  
  
)

server <- function(input,output) {
}

shinyApp(ui = ui,server = server)